Repository araceli4920/requisitos-segundo-parcial, pull requests merged in 2024-07, with the labels that each got.

#30 Se enlaza el contenido principal de la api
  index.html
  paises.js
Labels: enhancement

#31 Estilos CSS de paÍses
  img.paises/bandera2.jpg
  paises.css
  paises.html
  paises.js
Labels: enhancement

#33 Josue plata v implementacion del apiweatherleftcard
  weather.css
  weather.html
  weather.js
Labels: enhancement

#37 Se agrega rightcard de OpenWeather
  weather.css
  weather.html
Labels: enhancement

#38 Implementación del API WeatherRightCard
  weather.css
  weather.html
  weather.js
Labels: enhancement

#46 Se agregan los hipervínculos en la api de OpenWeather hacia las demás paginas
  weather.css
  weather.html
Labels: enhancement

#47 Implementación del Header de country
  paises.css
  paises.html
Labels: enhancement

#48 Implementacion de la pag.principal de paises
  img.paises/bandera2.jpg
  paises.css
  paises.html
  paises.js
Labels: documentation, enhancement

#49 Se agrega el paises_individual.html
  paises.css
  paises_individual.html
Labels: enhancement

#50 Se agrega el archivo js de la pagina individual
  paises.css
  paises.js
  paises_individual.html
  paises_individual.js
Labels: enhancement

#52 Implementación del buscador.html
  paises_buscador.html
Labels: documentation

#53 Se sube el js de la pagina buscador
  paises.html
  paises_buscador.html
  paises_buscador.js
  paises_individual.html
Labels: enhancement

#54 Se agrega interconexión entre weather y countries
  weather.html
  weather.js
Labels: enhancement

#57 Se vincula la api de rest countries a la de weather
  paises_buscador.js
  paises_individual.js
  weather.js
Labels: enhancement

#60 se han agregado los cambios en la card con los links.
  weather.css
Labels: enhancement

#61 Diego-Index-Responsivo
  ibackground.jpg
  index.css
  index.html
Labels: enhancement

#63 Diego-Links
  index.html
Labels: enhancement

#66 Opción enter en js de Buscador
  paises_buscador.js
Labels: bug, enhancement

#68 Se han agregado los cambios que el cliente ha solicitado
  index.css
  weather.css
  weather.html
Labels: enhancement

#70 HTML, CSS, JS Random user generator
  ramdomuser.css
  ramdomuser.html
  ramdomuser.js
Labels: help wanted

#71 Actualización de link
  index.html
Labels: documentation

#72 Responsivo de Weather
  weather.css
Labels: enhancement

#73 Se eliminan links sobrantes
  ramdomuser.html
  ramdomuser.js
  weather.css
  weather.html
Labels: enhancement

#74 Prueba para funcionamiento de Pages
  weather.html
Labels: bug, help wanted

#76 Se agrega buscar coordenadas
  weather.html
  weather.js
Labels: enhancement

#77 Modificacion de detalles de paises
  paises.css
  paises_buscador.css
  paises_individual.css
Labels: bug

#78 Se agrega el responsivo
  ramdomuser.css
Labels: enhancement

#80 responsivo
  paises_buscador.css
  paises_individual.css
Labels: enhancement
